const type = {

FETCH_POSTS: 'FETCH_POSTS',
FETCH_DETAIL_POSTS:'FETCH_DETAIL_POSTS',
ADD_TO_CART:'ADD_TO_CART',
UPDATE_CART_COUNT: 'UPDATE_CART_COUNT',
DELETE_FROM_CART:'DELETE_FROM_CART'
}

export default type;
